#logging:
#     file:
#       path: logs
#        name: ${logging.file.path}/app_CustomerProductCommand.log
#    level:
#        root: WARN
#        org.springframework.web: ERROR
#        ca.tmas.cpc: TRACE
#        org.hibernate: ERROR
#    pattern:
#        console: "(%d{ISO8601}) (%-5level) [(%t)] (%C{1.}): %msg%n%throwable"
#        file: "[%d{dd-MM-yyyy HH:mm:ss.SSS}] [%-5p|%c{1}] => ([%C{1.}], [%t], [%L]) %m%n"
server:
    port: 8040
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password:
        url: jdbc:mysql://localhost:3306/db_productcommandcustomer?useSSL=false
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            show_sql: true
            format_sql: true
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
            database-platform: org.hibernate.dialect.MySQL5Dialect
    jackson:
        serialization:
            write_dates_as_timestamps: false